name: Setup Python and Build Docs

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
      
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[doc]

    - name: Clone sphinx-build
      run: git clone https://github.com/dtdang/sphinx-build.git

    - name: Build HTML artifact
      run: |
        cd sphinx-build
        python build_docs.py
      env:
        GITHUB_REPO: ${{ env.GITHUB_REPO }}